openapi: 3.1.0
info:
    version: 1.0.0
    title: Contacts App
    license:
        name: Apache 2.0
        url: <http://www.apache.org/licenses/LICENSE-2.0.html>
    description: >
        Documantation of Contacts app api
tags:
    - name: Contacts
    description: Operations about users
    - name: Auth
    description: Auth Operations
    # kullanacağınız etiketler
servers:
    - url: <http://localhost:5173>
    - url: #yayınlanmış siteye bağlantı
paths:
    /contacts/{id}:
    get:
        $ref: ../swagger/paths/contacts/{id}/get.yaml
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
